### ISSUE TITLE
Update for GNOME Shell 3.16

### ISSUE THREAD

**Issue by nexfwall** [githubnemo/Pidgin-Persistent-Notification#8]
Subj.

**Comment by githubnemo** [comment]
Have you tried adding "3.16" in `metadata.json`? If it works, report back and I will publish the new version via extensions.gnome.org.

**Comment by nexfwall** [comment]
Tried. This just added the pidgin icon on the panel, what does nothing. And hides away pidgin icon from systray.

**Comment by githubnemo** [comment]
I see. Any errors when you run looking glass (lg)?

I would like to fix this but I have no GS 3.16 at hand at the moment, sorry.

**Comment by nexfwall** [comment]
>I would like to fix this but I have no GS 3.16 at hand at the moment, sorry.
I'm too, sorry. I have deleted it yesturday. I thought i could use it, but it seems GNOME Shell is too CPU hungry for me. 

Why just don't use GNOME Live image or Fedora Alpha 22 to test it, and fix errors?
